/**
 * @fileoverview gRPC-Web generated client stub for ssnet
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.6.1
// source: ssnet.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.ssnet = require('./ssnet_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ssnet.SSNetServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ssnet.SSNetServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ssnet.PayloadWithRes,
 *   !proto.ssnet.Empty>}
 */
const methodDescriptor_SSNetService_SendMsg = new grpc.web.MethodDescriptor(
  '/ssnet.SSNetService/SendMsg',
  grpc.web.MethodType.UNARY,
  proto.ssnet.PayloadWithRes,
  proto.ssnet.Empty,
  /**
   * @param {!proto.ssnet.PayloadWithRes} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ssnet.Empty.deserializeBinary
);


/**
 * @param {!proto.ssnet.PayloadWithRes} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ssnet.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ssnet.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ssnet.SSNetServiceClient.prototype.sendMsg =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ssnet.SSNetService/SendMsg',
      request,
      metadata || {},
      methodDescriptor_SSNetService_SendMsg,
      callback);
};


/**
 * @param {!proto.ssnet.PayloadWithRes} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ssnet.Empty>}
 *     Promise that resolves to the response
 */
proto.ssnet.SSNetServicePromiseClient.prototype.sendMsg =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ssnet.SSNetService/SendMsg',
      request,
      metadata || {},
      methodDescriptor_SSNetService_SendMsg);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ssnet.PayloadWithRes,
 *   !proto.ssnet.Payload>}
 */
const methodDescriptor_SSNetService_RecvMsg = new grpc.web.MethodDescriptor(
  '/ssnet.SSNetService/RecvMsg',
  grpc.web.MethodType.UNARY,
  proto.ssnet.PayloadWithRes,
  proto.ssnet.Payload,
  /**
   * @param {!proto.ssnet.PayloadWithRes} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ssnet.Payload.deserializeBinary
);


/**
 * @param {!proto.ssnet.PayloadWithRes} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ssnet.Payload)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ssnet.Payload>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ssnet.SSNetServiceClient.prototype.recvMsg =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ssnet.SSNetService/RecvMsg',
      request,
      metadata || {},
      methodDescriptor_SSNetService_RecvMsg,
      callback);
};


/**
 * @param {!proto.ssnet.PayloadWithRes} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ssnet.Payload>}
 *     Promise that resolves to the response
 */
proto.ssnet.SSNetServicePromiseClient.prototype.recvMsg =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ssnet.SSNetService/RecvMsg',
      request,
      metadata || {},
      methodDescriptor_SSNetService_RecvMsg);
};


module.exports = proto.ssnet;

